[rospy.client][INFO] 2025-06-11 11:04:16,639: init_node, name[/urdf_spawner], pid[30293]
[xmlrpc][INFO] 2025-06-11 11:04:16,639: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-11 11:04:16,639: Started XML-RPC server [http://192.168.1.124:36379/]
[rospy.init][INFO] 2025-06-11 11:04:16,639: ROS Slave URI: [http://192.168.1.124:36379/]
[rospy.impl.masterslave][INFO] 2025-06-11 11:04:16,639: _ready: http://192.168.1.124:36379/
[xmlrpc][INFO] 2025-06-11 11:04:16,640: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2025-06-11 11:04:16,640: Registering with master node http://localhost:11311
[rospy.init][INFO] 2025-06-11 11:04:16,740: registered with master
[rospy.rosout][INFO] 2025-06-11 11:04:16,740: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-11 11:04:16,742: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-11 11:04:16,745: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-11 11:04:16,748: connected to core topic /clock
[rosout][INFO] 2025-06-11 11:04:16,750: Loading model XML from ros parameter
[rosout][INFO] 2025-06-11 11:04:16,753: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2025-06-11 11:04:16,754: topic[/clock] adding connection to [http://192.168.1.124:38611/], count 0
[rosout][INFO] 2025-06-11 11:04:16,755: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2025-06-11 11:04:16,772: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name my_robot
[rospy.core][INFO] 2025-06-11 11:04:16,866: signal_shutdown [atexit]
[rospy.internal][INFO] 2025-06-11 11:04:16,868: topic[/clock] removing connection to http://192.168.1.124:38611/
[rospy.impl.masterslave][INFO] 2025-06-11 11:04:16,868: atexit
[rospy.internal][WARNING] 2025-06-11 11:04:16,869: Unknown error initiating TCP/IP socket to 192.168.1.124:47977 (http://192.168.1.124:38611/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

