[rospy.client][INFO] 2025-06-13 08:24:28,225: init_node, name[/urdf_spawner], pid[4157]
[xmlrpc][INFO] 2025-06-13 08:24:28,225: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-13 08:24:28,225: Started XML-RPC server [http://192.168.1.124:33085/]
[rospy.init][INFO] 2025-06-13 08:24:28,225: ROS Slave URI: [http://192.168.1.124:33085/]
[rospy.impl.masterslave][INFO] 2025-06-13 08:24:28,226: _ready: http://192.168.1.124:33085/
[rospy.registration][INFO] 2025-06-13 08:24:28,226: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2025-06-13 08:24:28,226: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2025-06-13 08:24:28,326: registered with master
[rospy.rosout][INFO] 2025-06-13 08:24:28,326: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-13 08:24:28,328: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-13 08:24:28,328: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-13 08:24:28,330: connected to core topic /clock
[rosout][INFO] 2025-06-13 08:24:28,333: Loading model XML from ros parameter
[rosout][INFO] 2025-06-13 08:24:28,335: Waiting for service /gazebo/spawn_urdf_model
[rosout][INFO] 2025-06-13 08:24:28,337: Calling service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2025-06-13 08:24:28,341: topic[/clock] adding connection to [http://192.168.1.124:44815/], count 0
[rosout][INFO] 2025-06-13 08:24:28,355: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name my_robot
[rospy.core][INFO] 2025-06-13 08:24:28,356: signal_shutdown [atexit]
[rospy.internal][INFO] 2025-06-13 08:24:28,358: topic[/clock] removing connection to http://192.168.1.124:44815/
[rospy.impl.masterslave][INFO] 2025-06-13 08:24:28,359: atexit
[rospy.internal][ERROR] 2025-06-13 08:24:28,366: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 730, in receive_once
    self.stat_bytes += recv_buff(sock, b, p.buff_size)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 103, in recv_buff
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

