[rospy.client][INFO] 2025-06-24 20:30:06,729: init_node, name[/urdf_spawner], pid[9706]
[xmlrpc][INFO] 2025-06-24 20:30:06,729: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2025-06-24 20:30:06,729: Started XML-RPC server [http://192.168.1.124:35243/]
[rospy.impl.masterslave][INFO] 2025-06-24 20:30:06,729: _ready: http://192.168.1.124:35243/
[rospy.init][INFO] 2025-06-24 20:30:06,730: ROS Slave URI: [http://192.168.1.124:35243/]
[rospy.registration][INFO] 2025-06-24 20:30:06,730: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2025-06-24 20:30:06,730: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2025-06-24 20:30:06,830: registered with master
[rospy.rosout][INFO] 2025-06-24 20:30:06,830: initializing /rosout core topic
[rospy.rosout][INFO] 2025-06-24 20:30:06,832: connected to core topic /rosout
[rospy.simtime][INFO] 2025-06-24 20:30:06,833: initializing /clock core topic
[rospy.simtime][INFO] 2025-06-24 20:30:06,837: connected to core topic /clock
[rosout][INFO] 2025-06-24 20:30:06,841: Loading model XML from ros parameter
[rosout][INFO] 2025-06-24 20:30:06,843: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2025-06-24 20:30:06,845: topic[/clock] adding connection to [http://192.168.1.124:46025/], count 0
[rosout][INFO] 2025-06-24 20:30:06,845: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2025-06-24 20:30:06,851: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name my_robot
[rospy.core][INFO] 2025-06-24 20:30:06,851: signal_shutdown [atexit]
[rospy.internal][INFO] 2025-06-24 20:30:06,856: topic[/clock] removing connection to http://192.168.1.124:46025/
[rospy.impl.masterslave][INFO] 2025-06-24 20:30:06,857: atexit
[rospy.internal][WARNING] 2025-06-24 20:30:06,858: Unknown error initiating TCP/IP socket to 192.168.1.124:58355 (http://192.168.1.124:46025/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

