[rospy.client][INFO] 2017-05-22 12:21:28,335: init_node, name[/kuka_arm/spawner], pid[3974]
[xmlrpc][INFO] 2017-05-22 12:21:28,336: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-05-22 12:21:28,336: Started XML-RPC server [http://udacity:40373/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:21:28,336: _ready: http://udacity:40373/
[rospy.init][INFO] 2017-05-22 12:21:28,336: ROS Slave URI: [http://udacity:40373/]
[xmlrpc][INFO] 2017-05-22 12:21:28,336: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-05-22 12:21:28,336: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-05-22 12:21:28,436: registered with master
[rospy.rosout][INFO] 2017-05-22 12:21:28,437: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:21:28,438: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:21:28,439: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:21:28,441: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:21:28,444: Controller Spawner: Waiting for service controller_manager/load_controller
[rospy.internal][INFO] 2017-05-22 12:21:28,720: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-05-22 12:21:28,767: topic[/clock] adding connection to [http://udacity:39105/], count 0
[rosout][INFO] 2017-05-22 12:21:29,652: Controller Spawner: Waiting for service controller_manager/switch_controller
[rosout][INFO] 2017-05-22 12:21:29,654: Controller Spawner: Waiting for service controller_manager/unload_controller
[rosout][INFO] 2017-05-22 12:21:29,655: Loading controller: joint_state_controller
[rosout][INFO] 2017-05-22 12:21:29,764: Loading controller: arm_controller
[rosout][INFO] 2017-05-22 12:21:29,918: Loading controller: gripper_controller
[rosout][INFO] 2017-05-22 12:21:30,074: Controller Spawner: Loaded controllers: joint_state_controller, arm_controller, gripper_controller
[rosout][INFO] 2017-05-22 12:21:30,077: Started controllers: joint_state_controller, arm_controller, gripper_controller
[rospy.core][INFO] 2017-05-22 12:22:03,524: signal_shutdown [signal-2]
[rosout][INFO] 2017-05-22 12:22:03,524: Shutting down spawner. Stopping and unloading controllers...
[rospy.internal][ERROR] 2017-05-22 12:22:03,734: Unable to initiate TCP/IP socket to udacity:54909 (http://udacity:39105/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 54909 to [127.0.0.1:52294 on socket 16]] [/kuka_arm/spawner].

[rosout][INFO] 2017-05-22 12:22:04,531: Stopping all controllers...
[rospy.internal][ERROR] 2017-05-22 12:22:04,736: Unable to initiate TCP/IP socket to udacity:54909 (http://udacity:39105/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 54909 to [127.0.0.1:52390 on socket 16]] [/kuka_arm/spawner].

[rospy.internal][ERROR] 2017-05-22 12:22:06,739: Unable to initiate TCP/IP socket to udacity:54909 (http://udacity:39105/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/clock] from [TCPROS connection on port 54909 to [127.0.0.1:52392 on socket 16]] [/kuka_arm/spawner].

[rosout][WARNING] 2017-05-22 12:22:10,146: Controller Spawner couldn't reach controller_manager to take down controllers. Waited for 30 second(s).
[rospy.internal][INFO] 2017-05-22 12:22:10,154: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-05-22 12:22:10,155: topic[/clock] removing connection to http://udacity:39105/
[rospy.impl.masterslave][INFO] 2017-05-22 12:22:10,155: signal-2
[rospy.core][INFO] 2017-05-22 12:22:10,774: signal_shutdown [atexit]
