[rospy.client][INFO] 2017-05-22 12:29:54,722: init_node, name[/urdf_spawner], pid[13004]
[xmlrpc][INFO] 2017-05-22 12:29:54,722: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-05-22 12:29:54,723: Started XML-RPC server [http://udacity:36329/]
[rospy.impl.masterslave][INFO] 2017-05-22 12:29:54,723: _ready: http://udacity:36329/
[rospy.registration][INFO] 2017-05-22 12:29:54,723: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-05-22 12:29:54,724: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-05-22 12:29:54,724: ROS Slave URI: [http://udacity:36329/]
[rospy.init][INFO] 2017-05-22 12:29:54,724: registered with master
[rospy.rosout][INFO] 2017-05-22 12:29:54,725: initializing /rosout core topic
[rospy.rosout][INFO] 2017-05-22 12:29:54,736: connected to core topic /rosout
[rospy.simtime][INFO] 2017-05-22 12:29:54,747: initializing /clock core topic
[rospy.simtime][INFO] 2017-05-22 12:29:54,754: connected to core topic /clock
[rosout][INFO] 2017-05-22 12:29:54,765: Loading model XML from ros parameter
[rosout][INFO] 2017-05-22 12:29:54,785: Waiting for service /gazebo/spawn_urdf_model
[rospy.internal][INFO] 2017-05-22 12:29:55,022: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-05-22 12:29:55,481: topic[/clock] adding connection to [http://udacity:46299/], count 0
[rosout][INFO] 2017-05-22 12:29:55,704: Calling service /gazebo/spawn_urdf_model
[rosout][INFO] 2017-05-22 12:29:56,168: Spawn status: SpawnModel: Successfully spawned entity
[rospy.core][INFO] 2017-05-22 12:29:56,168: signal_shutdown [atexit]
[rospy.internal][INFO] 2017-05-22 12:29:56,170: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-05-22 12:29:56,170: topic[/clock] removing connection to http://udacity:46299/
[rospy.internal][WARNING] 2017-05-22 12:29:56,171: Unknown error initiating TCP/IP socket to udacity:34821 (http://udacity:46299/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-05-22 12:29:56,171: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2017-05-22 12:29:56,171: atexit
